from abc import ABC, abstractmethod

class BaseLLMClient(ABC):
  """
  Abstract interface for all LLM providers-

  Implementations may include:
  - OpenAI
  - Ollama
  - Anthropic
  - Gemini
  """

  @abstractmethod
  def generate(
    self,
    system_prompt: str,
    user_prompt: str,
  ) -> str:
    """
    Generate a text response from an LLM.

    Parameters
    ----------
    system_prompt : str
      High-level instructions for the model.

    user_prompt : str
      Article-specific prompt.

    Returns
    -------
    str
      Raw response generated by the model.
    """

    raise NotImplementedError(
      "LLM providers must implement generate()."
    )
